gtccore/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

gtccore/gtccore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('accounts.urls')),

]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

gtccore/website/urls.py
from django.urls import path

from . import views

app_name = 'website'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('faqs/', views.FaqsView.as_view(), name='faqs'),
]

# applications
urlpatterns += [
    path('application/', views.ApplicationView.as_view(), name='application'),
    path('application/status/', views.ApplicationStatusView.as_view(), name='application_status'), #noqa
    path('application/download/', views.DownloadAdmissionLetterView.as_view(), name='download_letter'), #noqa
]

# courses
urlpatterns += [
    path('courses/', views.CoursesView.as_view(), name='courses'),
    path('courses-details/', views.CourseDetailsView.as_view(), name='course_details'), #noqa
    path('enroll/', views.EnrollView.as_view(), name='enroll'),
    path('enroll/success', views.EnrollSuccessView.as_view(), name='enroll_success'),
]

# payment
urlpatterns += [
    path('make-payment/', views.MakePaymentView.as_view(), name='make_payment'),
    path('upload-receipt/', views.UploadPaymentReceiptView.as_view(), name='upload_receipt'), #noqa
]

gtccore/website/views.py
from io import BytesIO

from django.db.models import Q
from django.http import FileResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views import View

from dashboard.forms import (ApplicationForm, ContactUsForm,
                             CustomCourseReguestForm, PaymentForm)
from dashboard.models import (Admission, Application, Comment, Course,
                              CourseCategory, Facilitator, Faq, Image,
                              ImageCategory, Testimonial)
from gtccore.library.constants import PaymentStatus


class HomeView(View):
    '''Home page view.'''
    template = 'website/index.html'

    def get(self, request):
        popular_courses = Course.objects.all().order_by('-id')[:5]
        team = Facilitator.objects.all().order_by('precedence')  # order by precedence
        testimonials = Testimonial.objects.all()
        images = Image.objects.all()

        gallery_categories = ImageCategory.objects.all()
        context = {
            'team': team,
            'testimonials': testimonials,
            'images': images,
            'popular_courses': popular_courses,
            'gallery_categories': gallery_categories

        }
        return render(request, self.template, context)


class ContactView(View):
    '''Contact page view.'''
    template = 'website/contact.html'

    def get(self, request):
        context = {}
        return render(request, self.template, context)
    
    def post(self, request):
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('website:contact')
        context = {}
        return render(request, self.template, context)
    

class FaqsView(View):
    '''FAQs page view.'''
    template = 'website/faqs.html'

    def get(self, request):
        faqs = Faq.objects.all()
        context = {
            'faqs': faqs
        }
        return render(request, self.template, context)
    

class ApplicationView(View):
    '''Application page view.'''
    template = 'website/application.html'

    def get(self, request):
        context = {}
        return render(request, self.template, context)
    

class ApplicationStatusView(View):
    '''Application Status page view.'''
    template = 'website/application_status.html'

    def get(self, request):
        application_id = request.GET.get('application_id')

        application = Application.objects.filter(
            Q(application_id=application_id.strip())
        ).first()

        context = {
            'application': application
        }
        return render(request, self.template, context)


class CoursesView(View):
    '''Courses page view.'''
    template = 'website/courses.html'

    def get(self, request):
        category_name = request.GET.get('category_name') or None
        category_id = request.GET.get('category_id') or None
        category = None
        # recently added courses: 5
        latst_courses = Course.objects.all().order_by('-id')[:5]
        query = request.GET.get('query')
        if query:
            categories = CourseCategory.objects.all()
            courses = Course.objects.filter(
                Q(title__icontains=query) |
                Q(description__icontains=query) |
                Q(details__icontains=query) |
                Q(cohort__name__icontains=query) |
                Q(requirements__icontains=query) |
                Q(syllabus__icontains=query) |
                Q(category__name__icontains=query) 
            ).order_by('start_date')
            context = {
                'category_name': query,
                'courses': courses,
                'categories': categories,
                'latst_courses': latst_courses
            }
            return render(request, self.template, context)
        # set all courses as default
        courses = Course.objects.all().order_by('start_date')
        if category_id:
            category_id = int(category_id)
            category = CourseCategory.objects.filter(id=category_id).first()

        if category:
            courses = Course.objects.filter(category=category).order_by('start_date')

        categories = CourseCategory.objects.all()
        context = {
            'category_name': category_name,
            'category': category,
            'courses': courses,
            'categories': categories,
            'latst_courses': latst_courses
        }
        return render(request, self.template, context)



class MakePaymentView(View):
    '''Make Payment page view.'''
    template = 'website/online-payment.html'

    def get(self, request):
        application_id = request.GET.get('application_id')
        application = Application.objects.filter(application_id=application_id).first() # noqa
        context = {
            'application': application
        }
        return render(request, self.template, context)
    
    def post(self, request):
        application_id = request.POST.get('application_id')
        application = Application.objects.filter(application_id=application_id).first() # noqa
        # implement payment logic here
        # implement payment logic here
        if application:
            # mimic successfull payment
            application.status = PaymentStatus.PAID.name
            application.save()
        return redirect('website:enroll_success')

class CourseDetailsView(View):
    '''Course Details page view.'''
    template = 'website/course-details.html'

    def get(self, request):
        course_id = request.GET.get('course_id')
        course_id = int(course_id)
        course = Course.objects.filter(id=course_id).first()
        comments = Comment.objects.filter(course=course)
        categories = CourseCategory.objects.all()
        context = {
            'course': course,
            'comments': comments,
            'categories': categories
        }
        return render(request, self.template, context)
    
    def post(self, request):
        form = CustomCourseReguestForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



class EnrollView(View):
    '''Enroll page view.'''
    template = 'website/enroll.html'
    template_make_payment = 'website/online-payment.html'
    template_duplicate = 'website/duplicate-enrollment.html'

    def get(self, request):
        course_id = request.GET.get('course_id')
        course_id = int(course_id)
        course = Course.objects.filter(id=course_id).first()
        context = {
            'course': course
        }
        return render(request, self.template, context)
    
    def post(self, request):
        form = ApplicationForm(request.POST, request.FILES)
        course_id = request.POST.get('course_id')
        pay_now = request.POST.get('pay_now')
        course_id = int(course_id)
        course = Course.objects.filter(id=course_id).first()
        if course is None:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        
        # check for duplicate enrollment
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        duplicate_application = Application.objects.filter(
            email=email,
            phone=phone,
            course=course
        ).first()
        if duplicate_application is not None:
            context = {"duplicate": duplicate_application}
            return render(request, self.template_duplicate, context)

        if form.is_valid():
            application = form.save(commit=False)
            application.course = course                
            application.save()
            context = {
                'application': application
            }
            if pay_now:
                # redirect to payment page
                return render(request, self.template_make_payment, context)
            return redirect('website:enroll_success')
        
        context = {
            'course': course
        }
        return render(request, self.template, context)


class EnrollSuccessView(View):
    '''Enroll Success page view.'''
    template = 'website/enroll-success.html'

    def get(self, request):
        context = {}
        return render(request, self.template, context)



class UploadPaymentReceiptView(View):
    '''Upload Payment Receipt view.'''
    template = 'website/online-payment.html'

    def get(self, request):
        application_id = request.GET.get('application_id')
        application = Application.objects.filter(application_id=application_id).first() # noqa
        context = {
            'application': application
        }
        return render(request, self.template, context)
    
    def post(self, request):
        application_id = request.POST.get('application_id')
        application = Application.objects.filter(application_id=application_id).first() # noqa
        if application:
            form = PaymentForm(request.POST, request.FILES)
            if form.is_valid():
                payment = form.save(commit=False)
                payment.application = application
                payment.save()
            return redirect('website:enroll_success')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


import datetime


class DownloadAdmissionLetterView(View):
    template = 'website/admission_letter.html'

    def get(self, request):
        application_id = request.GET.get('application_id')
        admission = Admission.objects.filter(application__application_id=application_id).first()
        todays_date = datetime.datetime.now()

        context = {
            'todays_date': todays_date,
            'admission': admission,
        }
        return render(request, self.template, context)

gtccore/website/templates/includes/alert.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

gtccore/website/templates/includes/footer.html
{% load static %}

 <!-- Footer -->
 <footer id="footer" class="footer divider layer-overlay overlay-dark-9" data-bg-img="{% static 'website/images/carousel/LMP-34.jpg' %}">
    <div class="container pt-70 pb-40">
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="widget dark">
                    <img class="mt-5 mb-20" alt="" src="{% static 'dashboard/assets/img/logo-white.png' %}" style="max-height: 85px;" />
                    <p>
                        GA 3413353 P. O. Box AH50 | Achimota, Accra, Ghana
                    </p>
                    <ul class="list-inline mt-5">
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-phone text-theme-colored2 mr-5"></i>
                            <a class="text-gray" href="#">+233 (0) 242 051 667</a>
                        </li>
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-phone text-theme-colored2 mr-5"></i>
                            <a class="text-gray" href="#">+233 (0) 246 015 233</a>
                        </li>
                    </ul>
                    
                    <ul class="list-inline mt-5">
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-phone text-theme-colored2 mr-5"></i>
                            <a class="text-gray" href="#">+233 (0) 245 440 800</a>
                        </li>
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-phone text-theme-colored2 mr-5"></i>
                            <a class="text-gray" href="#">+233 (0) 209 096 062</a>
                        </li>
                        <!-- <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-phone text-theme-colored2 mr-5"></i>
                            <a class="text-gray" href="#">+233 (0) 244 660 201</a>
                        </li> -->
                    </ul>
                    <ul class="list-inline mt-5">
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-phone text-theme-colored2 mr-5"></i>
                            <a class="text-gray" href="#">+233 (0) 501 432 842</a>
                        </li>
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-envelope-o text-theme-colored2 mr-5"></i>
                            <a class="text-gray" href="#">alet@gimpa.edu.gh</a>
                        </li>
                    </ul>
                    <!-- <ul class="list-inline mt-5">
                        
                    </ul> -->

                    <ul class="styled-icons icon-sm icon-bordered icon-circled clearfix mt-10">
                        <li>
                            <a href="https://www.facebook.com/share/2g8VeyAnfmAr1eTZ/?mibextid=WC7FNe" target="_blank"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/company/gimpatrainingandconsulting/" target="_blank"><i class="fa fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/p/C0KmxA4ISUW/?igshid=MTc4MmM1YmI2Ng==" target="_blank"><i class="fa fa-instagram"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="widget dark">
                    <h4 class="widget-title line-bottom-theme-colored-2">
                        Links
                    </h4>
                    <ul class="angle-double-right list-border">
                        <li><a href="{% url 'website:home' %}">Home</a></li>
                        <li><a href="{% url 'website:home' %}#about-gtc">About</a></li>
                        <li><a href="{% url 'website:home' %}#about-vision">Vision</a></li>
                        <li><a href="{% url 'website:faqs' %}">FAQ</a></li>
                    </ul>
                </div>
            </div>
    
            <div class="col-sm-6 col-md-4">
                <div class="widget dark">
                    <h4 class="widget-title line-bottom-theme-colored-2">
                        Hours
                    </h4>
                    <div class="opening-hours">
                        <ul class="list-border">
                            <li class="clearfix">
                                <span> Mon: </span>
                                <div class="value pull-right">8.00 am - 5.00 pm</div>
                            </li>
                            <li class="clearfix">
                                <span> Tues:</span>
                                <div class="value pull-right">8.00 am - 5.00 pm</div>
                            </li>
                            <li class="clearfix">
                                <span> Wed:</span>
                                <div class="value pull-right">8.00 am - 5.00 pm</div>
                            </li>
                            <li class="clearfix">
                                <span> Thur:</span>
                                <div class="value pull-right">8.00 am - 5.00 pm</div>
                            </li>
                            <li class="clearfix">
                                <span> Fri : </span>
                                <div class="value pull-right">8.00 pm - 5.00 pm</div>
                            </li>
                            <li class="clearfix">
                                <span> Sat : </span>
                                <div class="value pull-right">8.00 pm - 5.00 pm</div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom" data-bg-color="#2b2d3b">
        <div class="container pt-20 pb-20">
            <div class="row">
                <div class="col-md-6">
                    <p class="font-12 text-black-777 m-0 sm-text-center">
                        Copyright &copy; 2023 GTC. All Rights Reserved
                    </p>
                </div>
                <div class="col-md-6 text-right">
                    <div class="widget no-border m-0">
                        <ul class="list-inline sm-text-center mt-5 font-12">
                            <li>
                                <a href="{% url 'website:faqs' %}">FAQs</a>
                            </li>
                            <li>|</li>
                            <li>
                                <a href="{% url 'website:contact' %}">Help Desk</a>
                            </li>
                            <li>|</li>
                            <li>
                                <a href="{% url 'website:contact' %}">Support</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- / Footer -->

gtccore/website/templates/includes/header.html
{% load static %}

<header id="header" class="header">
    <div class="header-top sm-text-center primary-color">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="widget text-white">
                        <ul class="list-inline xs-text-center text-white">
                            <li class="m-0 pl-10 pr-10">
                                <a href="tel:+233242051667" class="text-white"><i class="fa fa-phone text-white"></i>
                                    +233 (0) 242 051 667</a>
                            </li>
                            <li class="m-0 pl-10 pr-10">
                                <a href="mailto:trainingandconsulting@gimpa.edu.gh" class="text-white"><i class="fa fa-envelope-o text-white mr-5"></i>
                                    trainingandconsulting@gimpa.edu.gh</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4 pr-0">
                    <div class="widget">
                        <ul class="styled-icons icon-sm pull-right flip sm-pull-none sm-text-center mt-5">
                            <li>
                                <a href="https://www.facebook.com/share/2g8VeyAnfmAr1eTZ/?mibextid=WC7FNe" target="_blank"><i class="fa fa-facebook text-white"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-twitter text-white"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-google-plus text-white"></i></a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/p/C0KmxA4ISUW/?igshid=MTc4MmM1YmI2Ng==" target="_blank"><i class="fa fa-instagram text-white"></i></a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/company/gimpatrainingandconsulting/" target="_blank"><i class="fa fa-linkedin text-white"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-2">
                    <ul class="list-inline sm-pull-none sm-text-center text-right text-white mb-sm-20 mt-10">
                        <li class="m-0 pl-10">
                            <a href="{% url 'accounts:login' %}" target="_blank" class="text-white"><i
                                    class="fa fa-user-o mr-5 text-white"></i> Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="header-nav">
        <div class="header-nav-wrapper navbar-scrolltofixed bg-white nav-lg">
            <div class="container">
                <nav id="menuzord-right" class="menuzord default no-bg">
                    <a class="menuzord-brand switchable-logo pull-left flip mt-20 pt-5" href="{% url 'website:home' %}">
                        <img class="logo-default" src="{% static 'dashboard/assets/img/logo-black.png' %}" style="height: 150px;" alt=""/>
                        <img class="logo-scrolled-to-fixed" src="{% static 'dashboard/assets/img/logo-black.png' %}" style="height: 150px;" alt=""/>
                    </a>
                    <ul class="menuzord-menu">
                        <li class="active">
                            <a href="{% url 'website:home' %}" class="primary-color">Home</a>
                        </li>
                        <li>
                            <a href="#">About Us</a>
                            <ul class="dropdown">
                                <li>
                                    <a href="{% url 'website:home' %}#about-gtc">GTC</a>
                                </li>
                                <li>
                                    <a href="{% url 'website:home' %}#about-team">Team</a>
                                </li>

                                <li>
                                    <a href="{% url 'website:home' %}#about-gallery">Gallery</a>
                                </li>
                                <li>
                                    <a href="{% url 'website:contact' %}">Contact</a>
                                </li>
                                <li>
                                    <a href="{% url 'website:faqs' %}">FAQs</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#courses">Courses</a>
                            <ul class="dropdown">

                                <li><a href="{% url 'website:courses' %}">Explore All</a></li>
                                {% for category in all_categories %}
                                <li><a
                                        href="{% url 'website:courses' %}?category_id={{category.id}}&category_name={{category.name}}">{{category.name}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'website:application' %}">Application Status</a>
                        </li>
                        <li>
                            <!-- search bar - Courses -->
                              <form action="{% url 'website:courses' %}" method="GET">
                                <div class="search-container">
                                    <div class="search-icon" id="searchIcon">
                                      <i class="fas fa-search"></i>
                                    </div>
                                    <input type="text" name="query" id="searchInput" placeholder="Search Courses">
                                    <label for="searchInput">Search...</label>
                                  </div>
                              </form> 
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

gtccore/website/templates/includes/scripts.html
{% load static %}

<!-- Footer Scripts -->
<!-- JS | Custom script for all pages -->
<script src="{% static 'website/js/custom.js' %}"></script>

<!-- SLIDER REVOLUTION 5.0 EXTENSIONS  
      (Load Extensions only on Local File Systems ! 
       The following part can be removed on Server for On Demand Loading) -->
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> -->
<script
  type="text/javascript"
  src="{% static 'website/js/revolution-slider/js/extensions/revolution.extension.actions.min.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'website/js/revolution-slider/js/extensions/revolution.extension.carousel.min.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'website/js/revolution-slider/js/extensions/revolution.extension.kenburn.min.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'website/js/revolution-slider/js/extensions/revolution.extension.layeranimation.min.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'website/js/revolution-slider/js/extensions/revolution.extension.migration.min.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'website/js/revolution-slider/js/extensions/revolution.extension.navigation.min.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'website/js/revolution-slider/js/extensions/revolution.extension.parallax.min.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'website/js/revolution-slider/js/extensions/revolution.extension.slideanims.min.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'website/js/revolution-slider/js/extensions/revolution.extension.video.min.js' %}"
></script>