gtccore/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('settings/preference', views.PreferenceSettingsView.as_view(), name='prefered_settings'), #noqa
    path('settings/password-reset', views.PasswordResetView.as_view(), name='password_reset'), #noqa
    path('settings/change-profile-pic', views.ChangeProfilePicView.as_view(), name='change_profile_pic'), #noqa
    path('profile/', views.UserProfileView.as_view(), name='profile'),
]

# users
urlpatterns += [
    path('users/', views.UsersView.as_view(), name='users'),
    path('user-details/', views.UserDetailsView.as_view(), name='user_details'),
    path('create-update-user/', views.CreateUpdateUser.as_view(), name='create_update_user'), #noqa
    path('update-user-pic/', views.UpdateUserProfilePicView.as_view(), name='update_profile_pic'), #noqa
    path('download-users/', views.DownloadUsersView.as_view(), name='download_users'), #noqa

    path('add-user-to-group/', views.AddUserToGroupsView.as_view(), name='add_user_to_group'), #noqa
    path('add-perm-to-user/', views.AddPermsToUserView.as_view(), name='add_perm_to_user'), #noqa
]


# applications
urlpatterns += [
    path('applications/', views.ApplicationsView.as_view(), name='applications'),
    path('create-application/', views.CreateApplicationView.as_view(), name='create_application'), #noqa
    path('admissions/', views.AdmissionsView.as_view(), name='admissions'),
    path('give-admission/', views.GiveAdmissionView.as_view(), name='give_admission'), #noqa
    path('admit-one-student/', views.AdmitOneStudentView.as_view(), name='admit_one_student'), #noqa
    path('applicants/', views.ApplicantsView.as_view(), name='applicants'),
    path('delete-applicant/', views.DeleteApplicantView.as_view(), name='delete_applicant'), #noqa

]


# downloads
urlpatterns += [
    path('download-applications/', views.DownloadApplicationsView.as_view(), name='download_applications'), #noqa
    path('download-applicants/', views.DownloadApplicantsView.as_view(), name='download_applicants'), #noqa
    path('download-admissions/', views.DownloadAdmissionsView.as_view(), name='download_admissions'), #noqa
    path('download-cohorts/', views.DownloadCohortView.as_view(), name='download_cohorts'), #noqa
    path('download-courses/', views.DownloadCoursesView.as_view(), name='download_courses'), #noqa
    path('download-categories/', views.DownloadCategoriesView.as_view(), name='download_categories'), #noqa
    path('download-notifications/', views.DownloadNotificationView.as_view(), name='download_notifications'), #noqa

]

# courses
urlpatterns += [
    path('courses/', views.CoursesView.as_view(), name='courses'),
    path('create-update-course/', views.CreateUpdateCourseView.as_view(), name='create_update_course'), #noqa
    path('create-update-category/', views.CreateUpdateCourseCategoryView.as_view(), name='create_update_category'), #noqa
    path('course-categories/', views.CourseCategoriesView.as_view(), name='course_categories'), #noqa
    path('cohorts/', views.CohortsView.as_view(), name='cohorts'), #noqa
    path('create-update-cohort/', views.CreateUpdateCohortView.as_view(), name='create_update_cohort'), #noqa
    path('delete-course/', views.DeleteCourseView.as_view(), name='delete_course'), #noqa
    path('delete-cohort/', views.DeleteCohortView.as_view(), name='delete_cohort'), #noqa
]


# payments
urlpatterns += [
    path('payments/', views.PaymentsView.as_view(), name='payments'),
    path('create-payment/', views.CreatePaymentView.as_view(), name='create_payment'), #noqa
    path('verify-payment/', views.ApproveDisapprovePaymentView.as_view(), name='verify_payment'), #noqa
    path('download-payments/', views.DownloadPaymentsView.as_view(), name='download_payments'), #noqa
]

#Support
urlpatterns += [
    path('contact-messages/', views.ContactMessagesView.as_view(), name='contact_messages'), #noqa
    path('contact-messages/reply/', views.ReplyMessageView.as_view(), name='reply_message'), #noqa
    path('download-contact-messages/', views.DownloadContactMessagesView.as_view(), name='download_contact_messages'), #noqa
    path('download-course-requests/', views.DownloadCourseRequestsView.as_view(), name='download_course_requests'), #noqa
    path('course-requests/', views.CourseRequestsView.as_view(), name='course_requests'), #noqa
    path('course-requests/reply/', views.ReplyCourseRequestView.as_view(), name='reply_course_request'), #noqa
    path('delete-request/', views.DeleteCourseRequestView.as_view(), name='delete_request'), #noqa
    path('notifications/', views.NotificationsView.as_view(), name='notifications'), #noqa
    path('create-update-notification/', views.CreateUpdateNotificationView.as_view(), name='create_update_notification'), #noqa
    path('broadcast-notification/', views.BroadcastNotificationView.as_view(), name='broadcast'), #noqa
    path('delete-notification/', views.DeleteNotificationView.as_view(), name='delete_notification'), #noqa
]

#Content Management
urlpatterns += [
    path('faqs/', views.FAQsView.as_view(), name='faqs'), #noqa
    path('create-update-faq/', views.CreateUpdateFAQView.as_view(), name='create_update_faq'), #noqa
    path('testimonials/', views.TestimonialsView.as_view(), name='testimonials'), #noqa
    path('create-update-testimonial/', views.CreateUpdateTestimonialView.as_view(), name='create_update_testimonial'), #noqa
    path('delete-faq/', views.DeleteFAQView.as_view(), name='delete_faq'), #noqa
    path('delete-testimonial/', views.DeleteTestimonialView.as_view(), name='delete_testimonial'), #noqa
    path('teams/', views.TeamsView.as_view(), name='teams'), #noqa
    path('create-update-team/', views.CreateUpdateTeamView.as_view(), name='create_update_team'), #noqa
    path('delete-team/', views.DeleteTeamView.as_view(), name='delete_team'), #noqa
    path('download-teams/', views.DownloadTeamsView.as_view(), name='download_teams'), #noqa
]

# gallery
urlpatterns += [
    path('image-categories/', views.ImageCategoriesView.as_view(), name='img_category'), #noqa
    path('create-update-img-cat/', views.CreateUpdateImageCategoryView.as_view(), name='create_update_img_cat'), #noqa
    path('images/', views.ImagesView.as_view(), name='images'), #noqa
    path('add-images/', views.AddImages.as_view(), name='add_images'), #noqa
    path('delete-image/', views.DeleteImageView.as_view(), name='delete_image'), #noqa
    path('delete-image-category/', views.DeleteImageCategoryView.as_view(), name='delete_img_cat'), #noqa
]

# groups and permissions
urlpatterns += [
    path('groups/', views.GroupsView.as_view(), name='groups'), #noqa
    path('create-update-group/', views.CreateUpdateGroupView.as_view(), name='create_update_group'), #noqa
    path('update-group-perm/', views.UpdatePermissionsToGroupView.as_view(), name='update_group_perm'), #noqa
    path('delete-group/', views.DeleteGroupView.as_view(), name='delete_group'), #noqa
]

gtccore/gtccore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('accounts.urls')),

]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

gtccore/dashboard/views/applications.py
import csv

from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from dashboard.forms import ApplicationForm
from dashboard.models import (Admission, Applicant, Application, Course,
                              CourseCategory)
from gtccore.library.constants import ApplicationStatus
from gtccore.library.decorators import StaffLoginRequired
from gtccore.library.logs import log_user_activity


class ApplicationsView(PermissionRequiredMixin, View):
    '''Applications view'''
    template = 'dashboard/pages/applications.html'
    permission_required = ['dashboard.view_application']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        query = request.GET.get('query')
        filtered = request.GET.get('form_id') == 'filter'
        applications = Application.objects.all().order_by('-created_at')
        course_categories = CourseCategory.objects.all().order_by('name')
        if query:
            query = query.strip()
            applications = applications.filter(
                Q(application_id__icontains=query) |
                Q(name__icontains=query) |
                Q(email__icontains=query) |
                Q(phone__icontains=query) |
                Q(course__title__icontains=query) |
                Q(application_status__icontains=query) |
                Q(payment_mode__icontains=query) |
                Q(payment_status__icontains=query)
            ).order_by('-created_at')
        
        if filtered:
            category = request.GET.get('category')
            start_date = request.GET.get('start_date')
            end_date = request.GET.get('end_date')
            if category == 'all':
                pass # All applications are already filtered
            else:
                applications = applications.filter(course__category__id=category)
            if start_date:
                applications = applications.filter(course__start_date__gte=start_date)
            if end_date:
                applications = applications.filter(course__start_date__lte=end_date)

        context = {
            'applications': applications,
            'categories': course_categories,
            'selected_category': request.GET.get('category') or 'all',
            'start_date': request.GET.get('start_date') or '',
            'end_date': request.GET.get('end_date') or '',
        }
        return render(request, self.template, context)


class CreateApplicationView(PermissionRequiredMixin, View):
    '''Create application view'''
    template = 'dashboard/pages/create-application.html'
    permission_required = [
        'dashboard.add_application',
        'dashboard.change_application',
    ]

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        courses = Course.objects.all().order_by('title')
        context = {
            'courses': courses,
        }
        return render(request, self.template, context)
    

    @method_decorator(StaffLoginRequired)
    def post(self, request):
        course_id = request.POST.get('course_id')
        course = Course.objects.filter(id=course_id).first()

        if not course:
            messages.error(request, 'Invalid Course')
            return redirect('dashboard:create_update_application')
        
        form = ApplicationForm(request.POST, request.FILES)
        if not form.is_valid():
            for k, v in form.errors.items():
                messages.error(request, f"{k}: {v}")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        new_application = form.save(commit=False)
        new_application.course = course                
        new_application.save()
        log_user_activity(request.user, 'Created application', None, new_application) # noqa
        messages.success(request, 'Application Created Successfully')
        return redirect('dashboard:applications')
    

class AdmissionsView(PermissionRequiredMixin, View):
    '''Admissions view'''
    template = 'dashboard/pages/admissions.html'
    permission_required = ['dashboard.view_admission']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        query = request.GET.get('query')
        admissions = Admission.objects.all().order_by('-created_at')
        if query:
            admissions = admissions.filter(
                Q(application__application_id__icontains=query) |
                Q(application__name__icontains=query) |
                Q(application__email__icontains=query) |
                Q(application__phone__icontains=query) |
                Q(application__course__title__icontains=query)
            ).order_by('-created_at')
        context ={
            'admissions': admissions,
        }
        return render(request, self.template, context)


class GiveAdmissionView(PermissionRequiredMixin, View):
    '''Give admission to applicant'''
    template = 'dashboard/pages/give-admission.html'
    permission_required = [
        'dashboard.add_admission',
    ]

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        pending_applications = Application.objects.filter(
            application_status=ApplicationStatus.PENDING.name
        ).count() # noqa
        approved_applications = Application.objects.filter(
            application_status=ApplicationStatus.APPROVED.name
        ).count() # noqa
        rejected_applications = Application.objects.filter(
            application_status=ApplicationStatus.REJECTED.name
        ).count() # noqa

        context = {
            'pending_applications': pending_applications,
            'approved_applications': approved_applications,
            'rejected_applications': rejected_applications,
        }
        return render(request, self.template, context)

    @method_decorator(StaffLoginRequired)
    def post(self, request):
        admission_type = request.POST.get('admission_type')

        applications = None
        if admission_type == 'pending':
            print('admitting pending applications')
            applications = Application.objects.filter(
                application_status=ApplicationStatus.PENDING.name
            ).order_by('-created_at')

        elif admission_type == 'all':
            print('admitting rejected applications')
            applications = Application.objects.filter(
                Q(application_status=ApplicationStatus.REJECTED.name) | 
                Q(application_status=ApplicationStatus.PENDING.name) # noqa
            ).order_by('-created_at')

        else:
            messages.error(request, 'Invalid Admission Type')
            return redirect('dashboard:give_admission')
        num_applications = applications.count()
        if applications:
            for application in applications:
                application.application_status = ApplicationStatus.APPROVED.name
                application.save()
            
            messages.success(request, f'{num_applications} Applications Admitted Successfully') # noqa
            return redirect('dashboard:give_admission')
        else:
            messages.error(request, 'No Applications Found')
            return redirect('dashboard:give_admission')
        

class AdmitOneStudentView(PermissionRequiredMixin, View):
    '''Admit just one student'''
    template = 'dashboard/pages/admit_one_student.html' 
    permission_required = [
        'dashboard.add_admission',
    ]

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        application_id = request.GET.get('application_id')
        application = Application.objects.filter(application_id=application_id).first() # noqa
        context = {
            'application': application
        }
        return render(request, self.template, context)
    
    @method_decorator(StaffLoginRequired)
    def post(self, request):
        application_id = request.POST.get('application_id')
        application = Application.objects.filter(application_id=application_id).first() # noqa
        if application:
            application.application_status = ApplicationStatus.APPROVED.name
            application.save()
            # log user activity
            log_user_activity(request.user, 'Admitted student', application, None) # noqa
            messages.success(request, 'Student Admitted Successfully')
        else:
            messages.error(request, 'Application Not Found')
        return redirect('dashboard:applications')


class ApplicantsView(PermissionRequiredMixin, View):
    '''applicants view'''
    template = 'dashboard/pages/applicants.html'
    permission_required = ['dashboard.view_applicant']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        query = request.GET.get('query')
        applicants = Applicant.objects.all().order_by('-created_at')
        if query:
            query = query.strip()
            applicants = applicants.filter(
                Q(name__icontains=query) |
                Q(email__icontains=query) |
                Q(phone__icontains=query)
            ).order_by('-created_at')
        context ={
            'applicants': applicants,
        }
        return render(request, self.template, context)
    
class DownloadApplicationsView(PermissionRequiredMixin, View):
    '''Download applications as csv'''
    permission_required = ['dashboard.view_application']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        filtered_download = request.GET.get('form_id') == 'filter'
        category = request.GET.get('category')
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')
        applications = Application.objects.all().order_by('-created_at')
        if filtered_download:

gtccore/dashboard/templates/dashboard/pages/courses.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<!-- Page Wrapper -->
<div class="page-wrapper">
    <div class="content container-fluid">

        <!-- Page Header -->
        <div class="page-header">
            <div class="content-page-header ">
                <h5>Courses</h5>
                <div class="list-btn">
                    <ul class="filter-list">
                        <li>
                            <a class="btn btn-filters w-auto popup-toggle" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-original-title="Search"><span class="me-2"><img src="{% static 'dashboard/assets/img/icons/filter-icon.svg' %}" alt="filter"></span>Search </a>
                        </li>

                        <li class="">
                            <div class="dropdown dropdown-action" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-original-title="Download">
                                <a href="#" class="btn-filters" data-bs-toggle="dropdown" aria-expanded="false"><span><i class="fe fe-download"></i></span></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <ul class="d-block">
                                        <li>
                                            <a class="d-flex align-items-center download-item" href="{% url 'dashboard:download_courses' %}" download><i class="far fa-file-text me-2"></i>CVS</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                      
                        <li>
                            <a class="btn btn-primary" href="{% url 'dashboard:create_update_course' %}"><i class="fa fa-plus-circle me-2" aria-hidden="true"></i>New Course</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        
         <!-- All Invoice -->
         <div class="card invoices-tabs-card">
            <div class="invoices-main-tabs">
                <div class="row align-items-center">
                    <div class="col-lg-12">
                        <div class="invoices-tabs">
                            <ul>
                                <li><a href="" class="active">Filter Courses</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /All Invoice -->

        <!-- filter section -->
        <div class="row">
            <div class="col-sm-12">
                <form action="" id="myForm" method="GET" style="display: inline;">

                    <input type="hidden" name="form_id" value="filter">
                    <div class="row">
                        <div class="col-3">
                            <label for="category">Course Category</label>
                            <select name="category" id="category" class="form-control">
                                <option value="all">All</option>
                                {% for cat in categories %}
                                <option value="{{cat.id}}" {% if cat.id == selected_category %} selected {% endif %} >{{cat.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
    
                        <div class="col-3">
                            <label for="">Start Date</label>
                            <input type="date" class="form-control" name="start_date">
                        </div>
    
                        <div class="col-3">
                            <label for="">End Date</label>
                            <input type="date" class="form-control" name="end_date">
                        </div>


                        <div class="col-1">
                            <label for="">Filter</label>
                            <button type="button" class="btn btn-sm btn-primary" onclick="setFormAction('courses')">Filter</button>
                        </div>
                        <div class="col-2">
                            <label for="">Download</label>
                            <button type="button" class="btn btn-sm btn-outline-primary" onclick="setFormAction('download_courses')">Download</button>
                        </div>

                    </div>
                    
                </form>

            </div>
        </div>

        <hr/>

        <!-- Table -->
        <div class="row">
            <div class="col-sm-12">
                <div class=" card-table">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-center table-hover datatable">
                                <thead class="thead-light">
                                    <tr>
                                        <th>#</th>
                                        <th>Thumbnail</th>
                                        <th>Title</th>
                                        <th>Category</th>
                                        <th>Cohort</th>
                                        <th>Price</th>
                                        <th>Start Date</th>
                                        <th>Duration</th>
                                        <th>Location</th>
                                        <th>Created At</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if courses %}
                                    {% for course in courses %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>
                                            <div class="avatar avatar-lg">
                                                <img src="{% if course.thumbnail %} {{course.thumbnail.url}} {% else %} {% static 'website/images/course/course-list1.jpg' %} {% endif %} " alt="Course Image" class="avatar-img rounded-circle">
                                            </div>
                                        </td>
                                        <td>{{course.title}}</td>
                                        <td>{{course.category.name}}</td>
                                        <td>{{course.cohort}}</td>
                                        <td>{{course.price}}</td>
                                        <td>{{course.start_date}}</td>
                                        <td>{{course.duration}}</td>
                                        <td>{{course.location}}</td>
                                        <td>{{course.created_at}}</td>
                                        <td class="d-flex align-items-center">
                                            <div class="dropdown dropdown-action">
                                                <a href="#" class=" btn-action-icon " data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <ul>
                                                        <li>
                                                            <a class="dropdown-item" href="{% url 'dashboard:create_update_course' %}?course_id={{course.id}}"><i class="far fa-edit me-2"></i>Edit</a>
                                                        </li>
                                                        <li>
                                                            <a class="dropdown-item" href="#"
                                                                onclick="confirmDelete('{{ course.id }}')">
                                                                <i class="far fa-trash-alt me-2"></i>Delete
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    {% else %}
                                    <tr>
                                        <td colspan="11" class="text-center">No Courses Found</td>
                                    </tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Table -->

    </div>
    <!-- Add Asset -->
    <div class="toggle-sidebar">
        <div class="sidebar-layout-filter">
            <div class="sidebar-header">
                <h5>Filter</h5>
                <a href="#" class="sidebar-closes"><i class="fa-regular fa-circle-xmark"></i></a>
            </div>
            <div class="sidebar-body">
                <form action="{% url 'dashboard:courses' %}" method="GET" autocomplete="off">
                    <!-- Product -->
                    <div class="accordion" id="accordionMain1">
                        <div class="card-header-new" id="headingOne">
                            <h6 class="filter-title">
                                <a href="javascript:void(0);" class="w-100" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Enter Search Query
                                    <span class="float-end"><i class="fa-solid fa-chevron-down"></i></span>
                                </a>
                            </h6>
                        </div>

                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample1">
                            <div class="card-body-chat">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div id="checkBoxes1">
                                            <div class="form-custom">
                                                <input type="text" class="form-control" id="member_search1" name="query" placeholder="Search Course">
                                                <span><img src="{% static 'dashboard/assets/img/icons/search.svg' %}" alt="img"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- /Product -->

                    <!-- /Category -->

                    <div class="filter-buttons">
                        <button type="submit" class="d-inline-flex align-items-center justify-content-center btn w-100 btn-primary">
                                Search
                            </button>
                        <button type="reset" class="d-inline-flex align-items-center justify-content-center btn w-100 btn-secondary">
                                Reset
                            </button>
                    </div>
                </form>

            </div>
        </div>
    </div>
    <!-- /Add Asset -->

    <!-- Delete Items alert confirmation -->
    <script>
        function confirmDelete(course_id) {
            if (confirm("Are you sure you want to delete this course?")) {
                // Redirect to the delete URL
                window.location.href = "{% url 'dashboard:delete_course' %}?course_id=" + course_id;
            }
        };

        function setFormAction(action) {
            if (action == 'download_courses') {
                window.location.href = "{% url 'dashboard:download_courses' %}?"+ $('#myForm').serialize();
                return;
            } else if (action == 'courses') {
                window.location.href = "{% url 'dashboard:courses' %}?"+ $('#myForm').serialize();
                return;
            }
        };
    </script>
    <!-- /Delete Items alert confirmation -->
</div>
<!-- /Page Wrapper -->
{% endblock %}