gtccore/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

gtccore/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('settings/preference', views.PreferenceSettingsView.as_view(), name='prefered_settings'), #noqa
    path('settings/password-reset', views.PasswordResetView.as_view(), name='password_reset'), #noqa
    path('settings/change-profile-pic', views.ChangeProfilePicView.as_view(), name='change_profile_pic'), #noqa
    path('profile/', views.UserProfileView.as_view(), name='profile'),
]

# users
urlpatterns += [
    path('users/', views.UsersView.as_view(), name='users'),
    path('user-details/', views.UserDetailsView.as_view(), name='user_details'),
    path('create-update-user/', views.CreateUpdateUser.as_view(), name='create_update_user'), #noqa
    path('update-user-pic/', views.UpdateUserProfilePicView.as_view(), name='update_profile_pic'), #noqa
    path('download-users/', views.DownloadUsersView.as_view(), name='download_users'), #noqa

    path('add-user-to-group/', views.AddUserToGroupsView.as_view(), name='add_user_to_group'), #noqa
    path('add-perm-to-user/', views.AddPermsToUserView.as_view(), name='add_perm_to_user'), #noqa
]


# applications
urlpatterns += [
    path('applications/', views.ApplicationsView.as_view(), name='applications'),
    path('create-application/', views.CreateApplicationView.as_view(), name='create_application'), #noqa
    path('admissions/', views.AdmissionsView.as_view(), name='admissions'),
    path('give-admission/', views.GiveAdmissionView.as_view(), name='give_admission'), #noqa
    path('admit-one-student/', views.AdmitOneStudentView.as_view(), name='admit_one_student'), #noqa
    path('applicants/', views.ApplicantsView.as_view(), name='applicants'),
    path('delete-applicant/', views.DeleteApplicantView.as_view(), name='delete_applicant'), #noqa

]


# downloads
urlpatterns += [
    path('download-applications/', views.DownloadApplicationsView.as_view(), name='download_applications'), #noqa
    path('download-applicants/', views.DownloadApplicantsView.as_view(), name='download_applicants'), #noqa
    path('download-admissions/', views.DownloadAdmissionsView.as_view(), name='download_admissions'), #noqa
    path('download-cohorts/', views.DownloadCohortView.as_view(), name='download_cohorts'), #noqa
    path('download-courses/', views.DownloadCoursesView.as_view(), name='download_courses'), #noqa
    path('download-categories/', views.DownloadCategoriesView.as_view(), name='download_categories'), #noqa
    path('download-notifications/', views.DownloadNotificationView.as_view(), name='download_notifications'), #noqa

]

# courses
urlpatterns += [
    path('courses/', views.CoursesView.as_view(), name='courses'),
    path('create-update-course/', views.CreateUpdateCourseView.as_view(), name='create_update_course'), #noqa
    path('create-update-category/', views.CreateUpdateCourseCategoryView.as_view(), name='create_update_category'), #noqa
    path('course-categories/', views.CourseCategoriesView.as_view(), name='course_categories'), #noqa
    path('cohorts/', views.CohortsView.as_view(), name='cohorts'), #noqa
    path('create-update-cohort/', views.CreateUpdateCohortView.as_view(), name='create_update_cohort'), #noqa
    path('delete-course/', views.DeleteCourseView.as_view(), name='delete_course'), #noqa
    path('delete-cohort/', views.DeleteCohortView.as_view(), name='delete_cohort'), #noqa
]


# payments
urlpatterns += [
    path('payments/', views.PaymentsView.as_view(), name='payments'),
    path('create-payment/', views.CreatePaymentView.as_view(), name='create_payment'), #noqa
    path('verify-payment/', views.ApproveDisapprovePaymentView.as_view(), name='verify_payment'), #noqa
    path('download-payments/', views.DownloadPaymentsView.as_view(), name='download_payments'), #noqa
]

#Support
urlpatterns += [
    path('contact-messages/', views.ContactMessagesView.as_view(), name='contact_messages'), #noqa
    path('contact-messages/reply/', views.ReplyMessageView.as_view(), name='reply_message'), #noqa
    path('download-contact-messages/', views.DownloadContactMessagesView.as_view(), name='download_contact_messages'), #noqa
    path('download-course-requests/', views.DownloadCourseRequestsView.as_view(), name='download_course_requests'), #noqa
    path('course-requests/', views.CourseRequestsView.as_view(), name='course_requests'), #noqa
    path('course-requests/reply/', views.ReplyCourseRequestView.as_view(), name='reply_course_request'), #noqa
    path('delete-request/', views.DeleteCourseRequestView.as_view(), name='delete_request'), #noqa
    path('notifications/', views.NotificationsView.as_view(), name='notifications'), #noqa
    path('create-update-notification/', views.CreateUpdateNotificationView.as_view(), name='create_update_notification'), #noqa
    path('broadcast-notification/', views.BroadcastNotificationView.as_view(), name='broadcast'), #noqa
    path('delete-notification/', views.DeleteNotificationView.as_view(), name='delete_notification'), #noqa
]

#Content Management
urlpatterns += [
    path('faqs/', views.FAQsView.as_view(), name='faqs'), #noqa
    path('create-update-faq/', views.CreateUpdateFAQView.as_view(), name='create_update_faq'), #noqa
    path('testimonials/', views.TestimonialsView.as_view(), name='testimonials'), #noqa
    path('create-update-testimonial/', views.CreateUpdateTestimonialView.as_view(), name='create_update_testimonial'), #noqa
    path('delete-faq/', views.DeleteFAQView.as_view(), name='delete_faq'), #noqa
    path('delete-testimonial/', views.DeleteTestimonialView.as_view(), name='delete_testimonial'), #noqa
    path('teams/', views.TeamsView.as_view(), name='teams'), #noqa
    path('create-update-team/', views.CreateUpdateTeamView.as_view(), name='create_update_team'), #noqa
    path('delete-team/', views.DeleteTeamView.as_view(), name='delete_team'), #noqa
    path('download-teams/', views.DownloadTeamsView.as_view(), name='download_teams'), #noqa
]

# gallery
urlpatterns += [
    path('image-categories/', views.ImageCategoriesView.as_view(), name='img_category'), #noqa
    path('create-update-img-cat/', views.CreateUpdateImageCategoryView.as_view(), name='create_update_img_cat'), #noqa
    path('images/', views.ImagesView.as_view(), name='images'), #noqa
    path('add-images/', views.AddImages.as_view(), name='add_images'), #noqa
    path('delete-image/', views.DeleteImageView.as_view(), name='delete_image'), #noqa
    path('delete-image-category/', views.DeleteImageCategoryView.as_view(), name='delete_img_cat'), #noqa
]

# groups and permissions
urlpatterns += [
    path('groups/', views.GroupsView.as_view(), name='groups'), #noqa
    path('create-update-group/', views.CreateUpdateGroupView.as_view(), name='create_update_group'), #noqa
    path('update-group-perm/', views.UpdatePermissionsToGroupView.as_view(), name='update_group_perm'), #noqa
    path('delete-group/', views.DeleteGroupView.as_view(), name='delete_group'), #noqa
]

gtccore/gtccore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('accounts.urls')),

]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

gtccore/dashboard/views/category.py
import csv

from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from dashboard.forms import CohortForm, CourseCategoryForm
from dashboard.models import Cohort, CourseCategory
from gtccore.library.decorators import StaffLoginRequired


class CourseCategoriesView(PermissionRequiredMixin, View):
    '''Course categories view'''
    template = 'dashboard/pages/course_categories.html'
    permission_required = ['dashboard.view_coursecategory']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        query = request.GET.get('query')
        categories = CourseCategory.objects.all().order_by('-id')
        if query:
            categories = CourseCategory.objects.filter(
                Q(name__icontains=query)
            ).order_by('-id')
        context ={
            'categories': categories
        }
        return render(request, self.template, context)
    

class CreateUpdateCourseCategoryView(PermissionRequiredMixin, View):
    '''Create and update course category view'''
    template = 'dashboard/pages/create-update-course-category.html'
    permission_required = [
        'dashboard.add_coursecategory', 
        'dashboard.change_coursecategory'
    ]

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        category_id = request.GET.get('category_id')
        category = None
        if category_id:
            category = CourseCategory.objects.filter(id=category_id).first()
        context = {
            'category': category
        }
        return render(request, self.template, context)
    
    @method_decorator(StaffLoginRequired)
    def post(self, request):
        category_id = request.POST.get('category_id')
        category = None
        if category_id:
            category = CourseCategory.objects.filter(id=category_id).first()
        form = CourseCategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            if category is None:
                messages.success(request, 'Category Created Successfully.')
                return redirect('dashboard:course_categories')
            messages.success(request, 'Category Updated Successfully.')
            return redirect('dashboard:course_categories')
        else:
            for k, v in form.errors.items():
                messages.error(request, f"{k}: {v}")
                return redirect('dashboard:course_categories')
    
class DownloadCategoriesView(PermissionRequiredMixin, View):
    '''Download categories as csv'''
    permission_required = ['dashboard.view_coursecategory']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        categories = CourseCategory.objects.all().order_by('-id')
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="categories.csv"'
        writer = csv.writer(response)
        writer.writerow(['name', 'created_at'])
        for category in categories:
            writer.writerow([category.name, category.created_at])
        return response
    

class CohortsView(PermissionRequiredMixin, View):
    template = 'dashboard/pages/cohorts.html'
    permission_required = ['dashboard.view_cohort']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        cohorts = Cohort.objects.all().order_by('-id')
        query = request.GET.get('query')
        if query:
            cohorts = Cohort.objects.filter(
                Q(name__icontains=query) | 
                Q(start_month__icontains=query)
            ).order_by('-id')
        context ={
            'cohorts': cohorts
        }
        return render(request, self.template, context)
    

class CreateUpdateCohortView(PermissionRequiredMixin, View):
    template = 'dashboard/pages/create-update-cohort.html'
    permission_required = [
        'dashboard.add_cohort',
        'dashboard.change_cohort'
    ]

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        cohort_id = request.GET.get('cohort_id')
        cohort = None
        if cohort_id:
            cohort = Cohort.objects.filter(id=cohort_id).first()

        months = ['January','February','March','April','May','June','July','August','September','October','November','December']
        context ={
            'months': months,
            'cohort': cohort
        }
        return render(request, self.template, context)
    
    @method_decorator(StaffLoginRequired)
    def post(self, request):
        cohort_id = request.POST.get('cohort_id')
        cohort = None
        if cohort_id:
            cohort = Cohort.objects.filter(id=cohort_id).first()
        form = CohortForm(request.POST, instance=cohort)
        if form.is_valid():
            form.save()
            if cohort is None:
                messages.success(request, 'Cohort created successfully.')
                return redirect('dashboard:cohorts')
            messages.success(request, 'Cohort Updated successfully.')
            return redirect('dashboard:cohorts')
        else:
            for k, v in form.errors.items():
                messages.error(request, f"{k}: {v}")
                return redirect('dashboard:cohorts')
    
class DownloadCohortView(PermissionRequiredMixin, View):
    '''Download cohorts as csv'''
    permission_required = ['dashboard.view_cohort']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        cohorts = Cohort.objects.all().order_by('-id')
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="cohorts.csv"'
        writer = csv.writer(response)
        writer.writerow(['name', 'start_month', 'created_at'])
        for cohort in cohorts:
            writer.writerow([cohort.name,cohort.start_month ,cohort.created_at])
        return response

gtccore/dashboard/views/contact_messages.py
import csv

from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View

from dashboard.models import Contact
from gtccore.library.decorators import StaffLoginRequired


class ContactMessagesView(PermissionRequiredMixin, View):
    '''Contact messages view'''
    template = 'dashboard/pages/contact_messages.html'
    permission_required = ['dashboard.view_contact']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        query = request.GET.get('query')
        contact_messages = Contact.objects.all().order_by('-id')
        print(contact_messages)
        if query:
            contact_messages = Contact.objects.filter(
                Q(name__icontains=query)
            ).order_by('-id')
        context ={
            'contact_messages': contact_messages
        }
        return render(request, self.template, context)

class ReplyMessageView(PermissionRequiredMixin, View):
    '''Reply message view'''
    template = 'dashboard/pages/reply_message.html'
    permission_required = ['dashboard.view_contact']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        message_id = request.GET.get('message_id')
        message = Contact.objects.filter(id=message_id).first()
        context = {
            'message': message
        }
        return render(request, self.template, context)
    
    @method_decorator(StaffLoginRequired)
    def post(self, request):
        message_id = request.POST.get('message_id')
        message = Contact.objects.filter(id=message_id).first()
        if not message:
            messages.error(request, 'Invalid Message.')
            return redirect('dashboard:contact_messages')
        reply_title = request.POST.get('reply_title')
        reply_message = request.POST.get('reply_message')
        success = message.reply_message(f"{reply_title}\n\n{reply_message}", mtype='sms')
        if success:
            # update message
            message.is_replied = True
            message.replied_message = f"{reply_title}\n\n{reply_message}"
            message.replied_by = request.user
            message.replied_at = timezone.now()
            message.save()
            messages.success(request, 'Message Replied Successfully.')
        else:
            messages.error(request, 'Failed to Reply Message.')
        return redirect('dashboard:contact_messages')
    
class DownloadContactMessagesView(PermissionRequiredMixin, View):
    '''Download contact messages view'''
    permission_required = ['dashboard.view_contact']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="contact_messages.csv"'
        writer = csv.writer(response)
        writer.writerow(['Name', 'Email', 'Phone', 'Message', 'Date'])
        messages = Contact.objects.all()
        for message in messages:
            writer.writerow([message.name, message.email, message.phone, message.message, message.created_at])
        return response

gtccore/dashboard/views/error.py
from django.shortcuts import render

def handler404(request, exception):
    template = 'error/404.html'
    return render(request, '404.html', status=404)


def handler500(request):
    template = 'error/404.html'
    return render(request, 'error/404.html', status=500)

gtccore/dashboard/templates/includes/dashboard_header.html
{% load static %}
<!-- Header -->
<div class="header header-one">

    <!-- Sidebar Toggle -->
    <a href="javascript:void(0);" id="toggle_btn">
            <span class="toggle-bars">
                <span class="bar-icons"></span>
                <span class="bar-icons"></span>
                <span class="bar-icons"></span>
                <span class="bar-icons"></span>
            </span>
        </a>
    <!-- /Sidebar Toggle -->

    <!-- Search -->
    <div class="top-nav-search">
        <form>
            <input type="text" class="form-control" placeholder="Search here">
            <button class="btn" type="submit"><img src="{% static 'dashboard/assets/img/icons/search.svg' %}" alt="img"></button>
        </form>
    </div>
    <!-- /Search -->

    <!-- Mobile Menu Toggle -->
    <a class="mobile_btn" id="mobile_btn">
            <i class="fas fa-bars"></i>
        </a>
    <!-- /Mobile Menu Toggle -->

    <!-- Header Menu -->
    <ul class="nav nav-tabs user-menu">
        
        <li class="nav-item dropdown  flag-nav dropdown-heads">
            <a class="nav-link" data-bs-toggle="dropdown" href="#" role="button">
                    <i class="fe fe-bell"></i> <span class="badge rounded-pill"></span>
                </a>
            <div class="dropdown-menu notifications">
                <div class="topnav-dropdown-header">
                    <span class="notification-title">Notifications</span>
                    <a href="javascript:void(0)" class="clear-noti"> Clear All</a>
                </div>
                <div class="noti-content">
                    <ul class="notification-list">
                    </ul>
                </div>
                <div class="topnav-dropdown-footer">
                    <a href="">View all Notifications</a>
                </div>
            </div>
        </li>
        <li class="nav-item  has-arrow dropdown-heads ">
            <a href="javascript:void(0);" class="win-maximize">
                    <i class="fe fe-maximize"></i>
                </a>
        </li>
        <!-- User Menu -->
        <li class="nav-item dropdown">
            <a href="javascript:void(0)" class="user-link  nav-link" data-bs-toggle="dropdown">
                    <span class="user-img">
                        <img src="{% if user.profile_pic %} {{user.profile_pic.url}} {% else %} {% static 'dashboard/assets/img/profiles/avatar-10.jpg' %} {% endif %}" alt="img" class="profilesidebar">
                        <span class="animate-circle"></span>
                    </span>
                    <span class="user-content">
                        {% if request.user %}
                        <span class="user-name">{{request.user.email}}</span>
                        {% else %}
                        <span class="user-name">Guest</span>
                        {% endif %}
                    </span>
                </a>
            <div class="dropdown-menu menu-drop-user">
                <div class="profilemenu">
                    <div class="subscription-menu">
                        <ul>
                            <li>
                                <a class="dropdown-item" href="{% url 'dashboard:settings' %}">Settings</a>
                            </li>
                        </ul>
                    </div>
                    <div class="subscription-logout">
                        <ul>
                            <li class="pb-0">
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log Out</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </li>
        <!-- /User Menu -->

    </ul>

    <!-- /Header Menu -->

    
{% for message in messages %}
<div class="row">
    <div class="col-12">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
    </div>
</div>
{% endfor %}

</div>
<!-- /Header -->

<!-- message -->

gtccore/dashboard/templates/includes/sidebar.html
{% load static %}
<!-- Sidebar -->
<div class="sidebar" id="sidebar" style="overflow-y: scroll;">
    <div class="sidebar-header">
        <div class="sidebar-logo">
            <a href="{% url 'dashboard:dashboard' %}">
                    <img class="logo-default" src="{% static 'dashboard/assets/img/logo-black.png' %}" style="height: 150px;" alt=""/>
                </a>
            <a href="{% url 'dashboard:dashboard' %}">
                    <img src="{% static 'website/images/gimpa-round-logo.jpg' %}" class="img-fluid logo-small" alt="">
                </a>
        </div>
    </div>
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <!-- Main -->
            <ul>
                <li class="menu-title"><span>Main</span></li>
                <li class="">
                    <a href="{% url 'dashboard:dashboard' %}"><i class="fe fe-home"></i> <span> Dashboard</span> <span class="menu-arrow"></span></a>
                </li>
            </ul>
            <!-- /Main -->

            <!-- Customers -->
            <ul>
                <li class="menu-title"><span>Applications</span></li>
                <li>
                    <a href="{% url 'dashboard:applications' %}"><i class="fe fe-users"></i> <span>Applications</span></a>
                </li>
                <li>
                    <a href="{% url 'dashboard:admissions' %}"><i class="fe fe-file"></i> <span>Admissions</span></a>
                </li>
                <li>
                    <a href="{% url 'dashboard:applicants' %}"><i class="fe fe-file"></i> <span>Applicants</span></a>
                </li>
            </ul>
            <!-- /Customers -->

            <!-- Purchases -->
            <ul>
                <li class="menu-title"><span>Courses</span></li>
                <li>
                    <a href="{% url 'dashboard:courses' %}"><i class="fe fe-shopping-cart"></i> <span>Courses</span></a>
                </li>
                <li>
                    <a href="{% url 'dashboard:cohorts' %}"><i class="fe fe-calendar"></i> <span>Cohorts</span></a>
                </li>
                <li>
                    <a href="{% url 'dashboard:course_categories' %}"><i class="fe fe-shopping-bag"></i> <span>Course Category</span></a>
                </li>
            </ul>
            <!-- /Purchases -->

            <!-- Finance & Accounts -->
            <ul>
                <li class="menu-title"><span>Finance & Accounts</span></li>
                <li>
                    <a href="{% url 'dashboard:payments' %}"><i class="fe fe-credit-card"></i> <span>Payments</span></a>
                </li>
            </ul>
            <!-- /Finance & Accounts -->


            <!-- User Management -->
            <ul>
                <li class="menu-title"><span>User Management</span></li>
                <li class="submenu">
                    <a href="#"><i class="fe fe-user"></i> <span> Manage Users</span> <span class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'dashboard:users' %}">Users</a></li>
                        <li><a href="{% url 'dashboard:groups' %}">Groups</a></li>
                    </ul>
                </li>
            </ul>
            <!-- /User Management -->


            <!-- Content (CMS) -->
            <ul>
                <li class="menu-title"><span>Content Management</span></li>
                <li class="submenu">
                    <a href="#"><i class="fe fe-folder"></i> <span> Gallery</span> <span class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'dashboard:images' %}">Images</a></li>
                        <li><a href="{% url 'dashboard:img_category' %}">Image Category</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'dashboard:teams' %}"><i class="fe fe-message-square"></i> <span>GTC Team</span></a>
                </li>
                <li>
                    <a href=""><i class="fe fe-message-square"></i> <span>Media Handles</span></a>
                </li>
                <li>
                    <a href="{% url 'dashboard:testimonials' %}"><i class="fe fe-message-square"></i> <span>Testimonials</span></a>
                </li>
                <li>
                    <a href="{% url 'dashboard:faqs' %}"><i class="fe fe-alert-circle"></i> <span>FAQs</span></a>
                </li>
            </ul>
            <!-- /Content (CMS) -->

            <!-- Support -->
            <ul>
                <li class="menu-title"><span>Support</span></li>
                <li>
                    <a href="{% url 'dashboard:contact_messages' %}"><i class="fe fe-printer"></i> <span>Contact Messages</span></a>
                </li>
                <li>
                    <a href="{% url 'dashboard:course_requests' %}"><i class="fe fe-printer"></i> <span>Custom Courses</span></a>
                </li>
                <li>
                    <a href="{% url 'dashboard:notifications' %}"><i class="fe fe-printer"></i> <span>Notifications</span></a>
                </li>
               
            </ul>
            <!-- /Support -->

            <!-- Settings -->
            <ul>
                <li class="menu-title"><span>Settings</span></li>
                <li>
                    <a href="{% url 'dashboard:settings' %}"><i class="fe fe-settings"></i> <span>Settings</span></a>
                </li>
                <li>
                    <a href="{% url 'accounts:logout' %}"><i class="fe fe-power"></i> <span>Logout</span></a>
                </li>
            </ul>
            <!-- /Settings -->

        </div>
    </div>
</div>
<!-- /Sidebar -->