gtccore/gtccore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('accounts.urls')),

]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

gtccore/website/urls.py
from django.urls import path

from . import views

app_name = 'website'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('faqs/', views.FaqsView.as_view(), name='faqs'),
]

# applications
urlpatterns += [
    path('application/', views.ApplicationView.as_view(), name='application'),
    path('application/status/', views.ApplicationStatusView.as_view(), name='application_status'), #noqa
    path('application/download/', views.DownloadAdmissionLetterView.as_view(), name='download_letter'), #noqa
]

# courses
urlpatterns += [
    path('courses/', views.CoursesView.as_view(), name='courses'),
    path('courses-details/', views.CourseDetailsView.as_view(), name='course_details'), #noqa
    path('enroll/', views.EnrollView.as_view(), name='enroll'),
    path('enroll/success', views.EnrollSuccessView.as_view(), name='enroll_success'),
]

# payment
urlpatterns += [
    path('make-payment/', views.MakePaymentView.as_view(), name='make_payment'),
    path('upload-receipt/', views.UploadPaymentReceiptView.as_view(), name='upload_receipt'), #noqa
]

gtccore/dashboard/views/applications.py
import csv

from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from dashboard.forms import ApplicationForm
from dashboard.models import (Admission, Applicant, Application, Course,
                              CourseCategory)
from gtccore.library.constants import ApplicationStatus
from gtccore.library.decorators import StaffLoginRequired
from gtccore.library.logs import log_user_activity


class ApplicationsView(PermissionRequiredMixin, View):
    '''Applications view'''
    template = 'dashboard/pages/applications.html'
    permission_required = ['dashboard.view_application']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        query = request.GET.get('query')
        filtered = request.GET.get('form_id') == 'filter'
        applications = Application.objects.all().order_by('-created_at')
        course_categories = CourseCategory.objects.all().order_by('name')
        if query:
            query = query.strip()
            applications = applications.filter(
                Q(application_id__icontains=query) |
                Q(name__icontains=query) |
                Q(email__icontains=query) |
                Q(phone__icontains=query) |
                Q(course__title__icontains=query) |
                Q(application_status__icontains=query) |
                Q(payment_mode__icontains=query) |
                Q(payment_status__icontains=query)
            ).order_by('-created_at')
        
        if filtered:
            category = request.GET.get('category')
            start_date = request.GET.get('start_date')
            end_date = request.GET.get('end_date')
            if category == 'all':
                pass # All applications are already filtered
            else:
                applications = applications.filter(course__category__id=category)
            if start_date:
                applications = applications.filter(course__start_date__gte=start_date)
            if end_date:
                applications = applications.filter(course__start_date__lte=end_date)

        context = {
            'applications': applications,
            'categories': course_categories,
            'selected_category': request.GET.get('category') or 'all',
            'start_date': request.GET.get('start_date') or '',
            'end_date': request.GET.get('end_date') or '',
        }
        return render(request, self.template, context)


class CreateApplicationView(PermissionRequiredMixin, View):
    '''Create application view'''
    template = 'dashboard/pages/create-application.html'
    permission_required = [
        'dashboard.add_application',
        'dashboard.change_application',
    ]

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        courses = Course.objects.all().order_by('title')
        context = {
            'courses': courses,
        }
        return render(request, self.template, context)
    

    @method_decorator(StaffLoginRequired)
    def post(self, request):
        course_id = request.POST.get('course_id')
        course = Course.objects.filter(id=course_id).first()

        if not course:
            messages.error(request, 'Invalid Course')
            return redirect('dashboard:create_update_application')
        
        form = ApplicationForm(request.POST, request.FILES)
        if not form.is_valid():
            for k, v in form.errors.items():
                messages.error(request, f"{k}: {v}")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        new_application = form.save(commit=False)
        new_application.course = course                
        new_application.save()
        log_user_activity(request.user, 'Created application', None, new_application) # noqa
        messages.success(request, 'Application Created Successfully')
        return redirect('dashboard:applications')
    

class AdmissionsView(PermissionRequiredMixin, View):
    '''Admissions view'''
    template = 'dashboard/pages/admissions.html'
    permission_required = ['dashboard.view_admission']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        query = request.GET.get('query')
        admissions = Admission.objects.all().order_by('-created_at')
        if query:
            admissions = admissions.filter(
                Q(application__application_id__icontains=query) |
                Q(application__name__icontains=query) |
                Q(application__email__icontains=query) |
                Q(application__phone__icontains=query) |
                Q(application__course__title__icontains=query)
            ).order_by('-created_at')
        context ={
            'admissions': admissions,
        }
        return render(request, self.template, context)


class GiveAdmissionView(PermissionRequiredMixin, View):
    '''Give admission to applicant'''
    template = 'dashboard/pages/give-admission.html'
    permission_required = [
        'dashboard.add_admission',
    ]

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        pending_applications = Application.objects.filter(
            application_status=ApplicationStatus.PENDING.name
        ).count() # noqa
        approved_applications = Application.objects.filter(
            application_status=ApplicationStatus.APPROVED.name
        ).count() # noqa
        rejected_applications = Application.objects.filter(
            application_status=ApplicationStatus.REJECTED.name
        ).count() # noqa

        context = {
            'pending_applications': pending_applications,
            'approved_applications': approved_applications,
            'rejected_applications': rejected_applications,
        }
        return render(request, self.template, context)

    @method_decorator(StaffLoginRequired)
    def post(self, request):
        admission_type = request.POST.get('admission_type')

        applications = None
        if admission_type == 'pending':
            print('admitting pending applications')
            applications = Application.objects.filter(
                application_status=ApplicationStatus.PENDING.name
            ).order_by('-created_at')

        elif admission_type == 'all':
            print('admitting rejected applications')
            applications = Application.objects.filter(
                Q(application_status=ApplicationStatus.REJECTED.name) | 
                Q(application_status=ApplicationStatus.PENDING.name) # noqa
            ).order_by('-created_at')

        else:
            messages.error(request, 'Invalid Admission Type')
            return redirect('dashboard:give_admission')
        num_applications = applications.count()
        if applications:
            for application in applications:
                application.application_status = ApplicationStatus.APPROVED.name
                application.save()
            
            messages.success(request, f'{num_applications} Applications Admitted Successfully') # noqa
            return redirect('dashboard:give_admission')
        else:
            messages.error(request, 'No Applications Found')
            return redirect('dashboard:give_admission')
        

class AdmitOneStudentView(PermissionRequiredMixin, View):
    '''Admit just one student'''
    template = 'dashboard/pages/admit_one_student.html' 
    permission_required = [
        'dashboard.add_admission',
    ]

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        application_id = request.GET.get('application_id')
        application = Application.objects.filter(application_id=application_id).first() # noqa
        context = {
            'application': application
        }
        return render(request, self.template, context)
    
    @method_decorator(StaffLoginRequired)
    def post(self, request):
        application_id = request.POST.get('application_id')
        application = Application.objects.filter(application_id=application_id).first() # noqa
        if application:
            application.application_status = ApplicationStatus.APPROVED.name
            application.save()
            # log user activity
            log_user_activity(request.user, 'Admitted student', application, None) # noqa
            messages.success(request, 'Student Admitted Successfully')
        else:
            messages.error(request, 'Application Not Found')
        return redirect('dashboard:applications')


class ApplicantsView(PermissionRequiredMixin, View):
    '''applicants view'''
    template = 'dashboard/pages/applicants.html'
    permission_required = ['dashboard.view_applicant']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        query = request.GET.get('query')
        applicants = Applicant.objects.all().order_by('-created_at')
        if query:
            query = query.strip()
            applicants = applicants.filter(
                Q(name__icontains=query) |
                Q(email__icontains=query) |
                Q(phone__icontains=query)
            ).order_by('-created_at')
        context ={
            'applicants': applicants,
        }
        return render(request, self.template, context)
    
class DownloadApplicationsView(PermissionRequiredMixin, View):
    '''Download applications as csv'''
    permission_required = ['dashboard.view_application']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        filtered_download = request.GET.get('form_id') == 'filter'
        category = request.GET.get('category')
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')
        applications = Application.objects.all().order_by('-created_at')
        if filtered_download:

gtccore/dashboard/views/faqs.py
import csv

from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from dashboard.models import Faq
from gtccore.library.decorators import StaffLoginRequired


class FAQsView(PermissionRequiredMixin, View):
    template = 'dashboard/pages/faqs.html'
    permission_required = ['dashboard.view_faq']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        query = request.GET.get('query')
        if query:
            faqs = Faq.objects.filter(
                Q(question__icontains=query) | 
                Q(answer__icontains=query)).order_by('-created_at') # noqa
        else:
            faqs = Faq.objects.all().order_by('-created_at')
        context ={
            'faqs': faqs
        }
        return render(request, self.template, context)
    
class CreateUpdateFAQView(PermissionRequiredMixin, View):
    template = 'dashboard/pages/create-update-faq.html'
    permission_required = [
        'dashboard.add_faq',
        'dashboard.change_faq'
    ]

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        faq_id = request.GET.get('faq_id')
        faq = None
        if faq_id:
            faq = Faq.objects.filter(id=faq_id).first()
        context = {
                'faq': faq
            }
        return render(request, self.template, context)

    @method_decorator(StaffLoginRequired)
    def post(self, request):
        question = request.POST.get('question')
        answer = request.POST.get('answer')
        faq_id = request.POST.get('faq_id')
        if faq_id:
            faq = Faq.objects.filter(pk=faq_id).first()
            faq.question = question
            faq.answer = answer
            faq.save()
            messages.success(request, 'FAQ updated successfully')
        else:
            faq = Faq.objects.create(
                question=question,
                answer=answer
            )
            messages.success(request, 'FAQ created successfully')
        return redirect(reverse('dashboard:faqs'))
    
class DeleteFAQView(PermissionRequiredMixin, View):
    '''Delete FAQ view'''
    permission_required = ['dashboard.delete_faq']

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        faq_id = request.GET.get('faq_id')
        faq = Faq.objects.filter(id=faq_id).first()
        if faq:
            faq.delete()
            messages.success(request, 'FAQ Deleted Successfully')
            return redirect(reverse('dashboard:faqs'))
        else:
            messages.error(request, 'FAQ Not Found')
            return redirect(reverse('dashboard:faqs'))

gtccore/website/templates/website/application_status.html
{% extends 'base/primary_base.html' %} {% load static %} {% block content %}
<!-- Start main-content -->
<div class="main-content">
    <!-- Section: inner-header -->
    <section class="inner-header divider layer-overlay overlay-theme-colored-7"
        data-bg-img="{% static 'website/images/carousel/LMP-30.jpg' %}">
        <div class="container pt-120 pb-60">
            <!-- Section Content -->
            <div class="section-content">
                <div class="row">
                    <div class="col-md-6">
                        <h2 class="secondary-text-color font-36">Application Status</h2>
                        <ol class="breadcrumb text-left mt-10 white">
                            <li><a href="{% url 'website:home' %}">Home</a></li>
                            <li>
                                <a href="{% url 'website:home' %}#about-gtc">Application</a>
                            </li>
                            <li class="active">Status</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Divider: Contact -->
    <section class="divider">
        <div class="container pt-50 pb-70">
            <div class="row pt-10">
                <div class="col-md-12">
                    <h4 class="mt-0 mb-30 line-bottom-theme-colored-2">
                        Your Application Status
                    </h4>
                    <!--  -->
                    <br />
                    <br />

                    <!-- details of application -->
                    <div class="card container">
                        <h4 class="text-center card-title">Application Details</h4>

                        {% if application %}
                        
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4 col-xs-12 text-left mb-5">
                                    <b>Name</b>
                                    <p>{{application.name}}</p>
                                </div>
                                <div class="col-md-4 col-xs- text-left mb-5">
                                    <b>Email</b>
                                    <p>{{application.email}}</p>
                                </div>
                                <div class="col-md-4 col-xs-12 text-left mb-5">
                                    <b>Phone</b>
                                    <p>{{application.phone}}</p>
                                </div>
                                <div class="col-md-4 col-xs-12 text-left mb-5">
                                    <b>Application ID</b>
                                    <p>{{application.application_id}}</p>
                                </div>
                                <div class="col-md-4 col-xs-12 text-left mb-5">
                                    <b>Application Status</b> <br>
                                    {% if application.application_status == "APPROVED" %}
                                    <p class="badge" style="background-color: green;">{{application.application_status}}</p>
                                    {% else %}
                                    <p class="badge bg-danger">{{application.application_status}}</p>
                                    {% endif %}
                                </div>
                                <div class="col-md-4 col-xs-12 text-left mb-5">
                                    <b>Course</b>
                                    <p>{{application.course.title}}</p>
                                </div>
                                <div class="col-md-4 col-xs-12 text-left mb-5">
                                    <b>Payment Mode</b>
                                    <p>{{application.payment_mode}}</p>
                                </div>
                                <div class="col-md-4 col-xs-12 text-left mb-5">
                                    <b>Payment Status</b> <br>
                                    {% if application.get_payment_status == "FULL PAYMENT" %}
                                    <p class="badge" style="background-color: green;">{{application.get_payment_status}}</p>
                                    {% elif application.payment_status == "PART PAYMENT" %}
                                    {% else %}
                                    <p class="badge bg-danger">{{application.get_payment_status}}</p>
                                    {% endif %}
                                </div>
                                <div class="col-md-4 col-xs-12 text-left mb-5">
                                    <b>Date</b>
                                    <p>{{application.created_at}}</p>
                                </div>
                                <div class="col-md-4 col-xs-12 text-left mb-5">
                                    <b>Total Paid</b>
                                    <p>GHC{{application.get_total_payments}}</p>
                                </div>
                                <div class="col-md-4 col-xs-12 text-left mb-5">
                                    <b>Payment History</b>
                                    {% for history in application.get_payment_history %}
                                    <p>GHC{{history.amount}} | {{history.date}}</p>
                                    {% endfor %}
                                </div>                                

                                <br>
                                {% if application.application_status == 'APPROVED' %}
                                <div class="col-12 mt-5">
                                    <a href="{% url 'website:download_letter' %}?application_id={{application.application_id}}" class="btn btn-sm btn-primary">Download Admission Letter</a>
                                </div>
                                {% endif %}
                                {% if application.get_payment_status != "FULL PAYMENT" %}
                                <div class="col-12 mt-5">
                                    <a href="{% url 'website:make_payment' %}?application_id={{application.application_id}}" class="btn btn-primary btn-sm">Pay For Application</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        {% else %}
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12">
                                    <p class="text-center">No Application Found</p>
                                </div>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- end main-content -->
{% endblock %}

gtccore/website/templates/website/online-payment.html
{% extends 'base/primary_base.html' %}

{% load static %}

{% block content %}
 <!-- Start main-content -->
 <div class="main-content">
    <!-- Section: inner-header -->
    <section class="inner-header divider layer-overlay overlay-theme-colored-7" data-bg-img="{% static 'website/images/bg/bg1.jpg' %}">
        <div class="container pt-120 pb-60">
            <!-- Section Content -->
            <div class="section-content">
                <div class="row">
                    <div class="col-md-6">
                        <h2 class="secondary-text-color font-36">Online Payment</h2>
                        <ol class="breadcrumb text-left mt-10 white">
                            <li><a href="{% url 'website:home' %}">Home</a></li>
                            <li><a href="{% url 'website:home' %}#about-gtc">Application</a></li>
                            <li class="active">Fee Payment</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Divider: Contact -->
    <section class="divider">
        <div class="container pt-50 pb-70">
            <div class="row pt-10">
                <div class="col-md-12">
                    <h4 class="mt-0 mb-30 line-bottom-theme-colored-2">Pay Your Application Fee Here</h4>

                    <div class="row">
                        <div class="col-md-4 mb-5">
                            <div class="box-hover-effect effect1 mb-sm-30">
                                <div class="caption">
                                    <h4 class="text-uppercase letter-space-1 mt-0">Application ID</h4>
                                    <p class="text-gray-dimgray font-13 mb-20">{{application.application_id}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 mb-5">
                            <div class="box-hover-effect effect1 mb-sm-30">
                                <div class="caption">
                                    <h4 class="text-uppercase letter-space-1 mt-0">Course</h4>
                                    <p class="text-gray-dimgray font-13 mb-20">{{application.course.title}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 mb-5">
                            <div class="box-hover-effect effect1 mb-sm-30">
                                <div class="caption">
                                    <h4 class="text-uppercase letter-space-1 mt-0">Duration</h4>
                                    <p class="text-gray-dimgray font-13 mb-20">{{application.course.start_date}} - {{application.course.end_date}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 mb-5">
                            <div class="box-hover-effect effect1 mb-sm-30">
                                <div class="caption">
                                    <h4 class="text-uppercase letter-space-1 mt-0">Name</h4>
                                    <p class="text-gray-dimgray font-13 mb-20">{{application.name}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 mb-5">
                            <div class="box-hover-effect effect1 mb-sm-30">
                                <div class="caption">
                                    <h4 class="text-uppercase letter-space-1 mt-0">Email</h4>
                                    <p class="text-gray-dimgray font-13 mb-20">{{application.email}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 mb-5">
                            <div class="box-hover-effect effect1 mb-sm-30">
                                <div class="caption">
                                    <h4 class="text-uppercase letter-space-1 mt-0">Phone</h4>
                                    <p class="text-gray-dimgray font-13 mb-20">{{application.phone}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <!-- NOTE: UNCOMMENT THE ONLINE PAYMENT IMPLEMENTATION -->
                    {% comment %}
                    <small class="secondary-text-color mb-5">Make sure you've verified the application before making payment.</small> 
                    <!--  -->
                    <br> <br>
                    <!-- Contact Form -->
                    <form id="contact_form" name="contact_form" action="{% url 'website:make_payment' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="application_id" value="{{application.application_id}}">

                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group mb-30">
                                    <input id="phone" name="phone" class="form-control" type="text" placeholder="Phone Number" required>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group mb-30">
                                    <select name="network" id="network" class="form-control">
                                        <option value="MTN">MTN</option>
                                        <option value="VOD">Vodafone</option>
                                        <option value="AIR">Airtel Tigo</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group mb-30">
                                    <input id="amount" name="amount" value="{{application.course.price}}" class="form-control required" type="text" placeholder="Amount" required {% if application.course.allows_part_payment %} readonly {% endif %}>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-flat btn-default primary-color text-white bg-hover-theme-colored mr-5" data-loading-text="Please wait...">Make Payment</button>
                            <button type="reset" class="btn btn-flat btn-danger bg-hover-theme-colored">Reset</button>
                        </div>
                    </form>
                    <!--  -->
                    {% endcomment %}
                    <hr>
                    <small class="secondary-text-color mb-5">Already paid at the Bank? Go ahead and upload the receipt.</small> 
                    <br> <br>
                    <!-- Contact Form -->
                    <form id="contact_form" name="contact_form" action="{% url 'website:upload_receipt' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="application_id" value="{{application.application_id}}">
                        <input type="hidden" name="network" value="BANK">
                        <input type="hidden" name="number" value="010-1763730">
                        <input type="hidden" name="status_code" value="104">
                        <input type="hidden" name="status_message" value="Pending Institution's Approval">

                        <div class="row">
                           
                            <div class="col-sm-4">
                                <div class="form-group mb-30">
                                    <input id="amount" name="amount" value="" class="form-control required" type="text" placeholder="Amount" required>
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="form-group mb-30">
                                    <input type="file" class="form-control" name="receipt" accept="image/*" onchange="displayImagePreview(this)" required>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group mb-30">
                                    <img id="image-preview" src="" alt="Receipt Preview" style="max-width: 100%; max-height: 150px; margin-top: 10px;">
                                </div>
                            </div>
    
                        </div>
                       
                        <div class="form-group">
                            <button type="submit" class="btn btn-flat btn-default primary-color text-white bg-hover-theme-colored mr-5" data-loading-text="Please wait...">Upload Receipt</button>
                            <button type="reset" class="btn btn-flat btn-danger bg-hover-theme-colored">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- end main-content -->


<script>
    function displayImagePreview(input) {
        var preview = document.getElementById('image-preview');
        var file = input.files[0];

        if (file) {
            var reader = new FileReader();
            reader.onload = function (e) {
                preview.src = e.target.result;
            };
            reader.readAsDataURL(file);
        } else {
            preview.src = "";
        }
    }
</script>
{% endblock %}